### ISSUE TITLE
Edge 类 

### ISSUE THREAD

**Issue by TwiceMao** [Wajov/HiddenSurfaceRemover#1]
请问在 Edge 类的构造函数里面
dz dp dn 为什么都要除以 deltaY 呢？

**Comment by Wajov** [comment]
dz dp dn应该是表示向右移动一个像素的时候深度、世界坐标和法向的变化量，所以要除以deltaY

**Comment by TwiceMao** [comment]
好的，我明白你的意思了。
那你的 y 轴是向右的，请问你的坐标系轴向是？

**Comment by Wajov** [comment]
没记错的话x轴是纵向的，y轴是横向的，z轴是垂直于屏幕空间的

**Comment by TwiceMao** [comment]
嗯嗯你这个坐标轴是什么传统啊？跟 OpenCV 和 OpenGL的都不一样哈哈哈
基于OpenCV的和OpenGL的坐标轴向分别是
[right, down, forwards]

![image](https://user-images.githubusercontent.com/43490149/210931484-4fea6566-cfae-449f-a553-e3f5f146858c.png)

和[right, up, backwards]
![image](https://user-images.githubusercontent.com/43490149/210931509-8ab99b5a-d8af-4148-ab4b-38357536b38a.png)
