### ISSUE TITLE
ActivePolygon 类

### ISSUE THREAD

**Issue by TwiceMao** [Wajov/HiddenSurfaceRemover#2]
请教一下，在你的 ActivePolygon 类的构造函数里面
leftY rightY 为什么是用相邻的两根 edge 的 target vertex 的 y呢？
不太明白它的含义，
此外为什么要有 if (edge.getDeltaY() > 0)的判断和 index 变量呢？
真的很麻烦您了，谢谢您~

**Comment by Wajov** [comment]
之前弄错了，y轴应该是纵向的
leftY和rightY维护的是多边形和当前扫描线相交的两根线段的最下面的点的y坐标，用来判断什么时候这跟线段跟扫描线解除相交
 if (edge.getDeltaY() > 0)的判断是用来剔除水平的线段，这种线段不会参与与扫描线的相交
index变量用来保存当前多边形已经有几根线段跟扫描线相交，当left和right两根线段中有线段跟扫描线解除相交的时候就从还未相交的线段中找新的相交线段
